@echo off
echo Starting Dire Foods App...
echo.
echo Starting Backend...
start cmd /k "cd backend && npm run dev"
timeout /t 3
echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
timeout /t 5
echo Opening browser...
start http://localhost:5173
echo.
echo App is running! Don't close the terminals.